[package]
name = "custos-math"
version = "0.1.1"
edition = "2021"
license = "MIT"
categories = ["mathematics", "science"]
keywords = ["CUDA", "OpenCL", "arrays", "matrices", "deep-learning"]
description = "Natrix operations with custos"
readme = "README.md"
repository = "https://github.com/elftausend/custos-math"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#custos = {git = "https://github.com/elftausend/custos"}
#custos = { path = "../custos", default-features = false }
custos = { version = "0.1.4", default-features = false }
fastrand = "1.7.0"

[features]
default = ["opencl"]
safe = ["custos/safe"]
opencl = ["custos/opencl"]
cuda = ["custos/cuda"]


[[example]]
name = "simple"
required-features = ["opencl"]