[package]
name = "custos-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#custos = {git = "https://github.com/elftausend/custos"}
custos = { path = "../custos", default-features = false }
rand = "0.8.5"

[features]
default = ["opencl"]
safe = []
opencl = ["custos/opencl"]
cuda = ["custos/cuda"]
