[package]
name = "custos-math"
version = "0.1.4"
edition = "2021"
license = "MIT"
categories = ["mathematics", "science"]
keywords = ["CUDA", "OpenCL", "arrays", "matrices", "deep-learning"]
description = "Matrix operations with custos"
readme = "README.md"
repository = "https://github.com/elftausend/custos-math"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#custos = {git = "https://github.com/elftausend/custos"}
custos = { path = "../custos", default-features = false }
#custos = { version = "0.2.1", default-features = false }
fastrand = "1.7.0"

[features]
default = []
opencl = ["custos/opencl"]
cuda = ["custos/cuda"]
realloc = ["custos/realloc"]


[[example]]
name = "simple"
required-features = ["opencl"]

[[test]]
name = "switching"
required-features = ["opencl"]