name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --no-default-features
    - name: Build - safe
      run: cargo build --verbose --no-default-features --features safe
    - name: Run tests
      run: cargo test --verbose --no-default-features
    - name: Run tests
      run: cargo test --verbose --no-default-features --features safe
